Step 1: Controllers films users
SidyakinV/java-filmorate pull request #6
Opened 2024-02-08 04:55 UTC by SidyakinV

2024-02-08 09:50 UTC, TomattmanYandex requested changes
Привет, отличная работа, из важных моментов на исправление это то, где находится метод на валидацию, все остальное это моменты на улучшение

2024-02-08 09:50 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film copy() {
пока не очень понятно зачем этот метод, я думаю я еще разберусь в этом, но почитай в интеренете про интерфейс Clonable и Object.clone()

2024-02-08 09:50 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/managers/memory/InMemoryFilmsManager.java
> +public class InMemoryFilmsManager implements FilmsManager {
если на строчку выше добавить аннотацию @Service или @Repository то...
(Тут шутка про кликбейтную рекламу) продолжение смотри в комментариях к контроллеру)

2024-02-08 09:50 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping
обычно в Rest , запросы относящиеся к конкретному объекту, например получение объекта по идентификатору, изменение объекта по идентификатору и т.д. имеют в пути идентификатор этого обьекта
например
GET /films/{id} вернет фильм с идентификатором переданным в пути
PUT /films/{id} обновит фильм с идентификатором переданным в пути

гуглить по запросу
pathvariable spring

2024-02-10 04:16 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void validate() throws ValidationException {
К сожалению, тупо не успел разобраться с аннотациями - просто понапихав их, они не заработали. Поэтому решил сделать отдельным методом. И здесь уже исходил из следующих моментов. Первый - если аннотации относятся к модели, то и метод валидирования логичнее всего расположить там же. Второе - мы описываем объект, и говорим, что его базовые характеристики должны быть именно такими, как мы и предусмотрели, а не давать на откуп разным контроллерам. Контроллеров может быть много, зачем в каждый из них тащить один и тот же метод валидации. Третье - можно сделать юнит-тест на конкретный объект, и протестировать все его возможные состояния. 
В общем, как скажешь - надо перенести, перенесу.

2024-02-10 04:34 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film copy() {
По опыту прошлого задания, очень неудобно, когда все объекты ссылаются по сути на один и тот же объект. Особенно это касается тестирования. Поэтому решил работать с клонами.
Сам clone() я уже попробовал использовать в прошлом задании. Однако клонирование может быть поверхностным, и глубоким. Поверхностное не решает моих задач, а глубокое требует клонирования всех ссылочных переменных, входящих в объект.
В инете нашел рекомендацию, что для этих целей можно использовать сериализацию/десериализацию, что гарантирует создание абсолютно нового объекта при минимуме кода. Решил попробовать.

2024-02-10 08:12 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmsManager films;
Ооо, магия вне Хогвартса.
Прикольно, но пока еще не совсем понятно, нафига. Наверное, я ретроград. :)

2024-02-10 08:19 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping
Вот да, здесь полностью согласен, обычно ровно так и делается. И в теории описано так.
Именно так и сделал, но... Не заработали тесты, прилагаемые к заданию для Postman'а.
Пришлось реализацию подгонять под тесты.

2024-02-11 13:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public Film copy() {
отлично, однако уже в следующих спринтах вы уже будете работать с базами данных и через Rest api взаимодействовать, так что проблема уже будет не актуальна 
(Все отлично)

2024-02-11 13:52 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void validate() throws ValidationException {
В реальных проектах обычно используется валидирование аннотациями, поэтому там таких проблем нету, везде где используется этот обьект, будет одинаковая валидация,
второй момент, чаще всего есть два обьекта, DTO которые как раз таки приходят на вход в контроллеры, и объекты сущности, и валидируются, именно Dto
Третье, чаще всего один контроллер один объект с которым он работает, поэтому нету проблемы с тем что будет несколько одинаковых методов
Ну и последнее, существует концепция согласно которой, классы моделей не должны иметь никакой логики, кроме стандартных переопределений, а вся логика должна быть выполнена на уровне сервисов

2024-02-11 13:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmsManager films;
Это тоже один из подходов облегчающих работу с кодом
почитай про сильную и слабую связность в коде

2024-02-11 13:58 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @PutMapping
совсем забываю про тесты постмана

2024-02-11 13:58 UTC, TomattmanYandex approved these changes
ПРинято

2024-02-13 02:34 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private InMemoryFilmsManager films;
это не films) старайся называть более понятно переменные зависимостей. Это inMemoryFilmsManager

2024-02-13 02:34 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public static void validate(Film film) throws ValidationException {
private и не static. Старайся не делать статики в бинах спринга

2024-02-13 02:34 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UsersManager users;
usersManager

2024-02-13 02:34 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @PutMapping()
() можно не ставить, если нет параметров

2024-02-13 02:34 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public static void validate(User user) throws ValidationException {
просто private

2024-02-18 03:02 UTC, merged