Add friends likes
SidyakinV/java-filmorate pull request #7
Opened 2024-02-24 06:12 UTC by SidyakinV

2024-02-24 14:54 UTC, TomattmanYandex requested changes
Хорошая работа
жду улучшений)))

2024-02-24 14:54 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
можно еще сделать private final и инжектить через конструктор
а так как вы используете ломбук то можно private final и @RequiredArgsConstructor над классом

2024-02-24 14:54 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private FilmStorage filmStorage;
тут аналогично как и в контроллерах можно инжектить

2024-02-24 14:54 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    @SuppressWarnings("unused")
если он не используется то зачем его добавлять, а если он используется, то зачем игнорировать варнинги на неиспользование?

2024-02-24 14:54 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film == null) {
аналогично и для юзеров

2024-02-24 14:54 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        film.getUserLikes().add(userStorage.getUser(userId).getId());
про ошибку написал в хранилище, еще хороший вариант, инжектить сюда, не хранилище юзеров, а сервис юзеров, а уже чтобы сервис юзеров, при не нахождении бросал ошибку

2024-02-25 18:21 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    @SuppressWarnings("unused")
Добавил эту аннотацию, т.к. Идея постоянно ругалась на варнинги при коммите. 
Ну в контроллерах еще понятно - методы действительно замапплены, и явно не вызываются, типа не используются.
А вот почему в сервисах filmService и userService переменные filmStorage и userStorage были серыми, несмотря на то, что они явно использовались во всех методах в этих классах - непонятно. Кстати, после того, как добавил аннотацию @RequiredArgsConstructor, варнинги пропали.
В любом случае, неприятно, что Идея ругается на них.

2024-02-26 04:44 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private FilmService filmService;
пожалуйста обрати внимание на этот комментарий. Инъекцию зависимостей в проекте мы делаем только через конструктор

2024-02-26 04:44 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
обрат внимание на этот комментарий. Есть более современный способ для обработки ошибок. Нужно создать контролер помеченный аннотацией @ControllerAdvice и все обработчики ошибок вынести в него

2024-02-26 04:44 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private UserService userService;
private final и инъекция через конструктор

2024-02-26 04:44 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ExceptionHandler
вынести обработчики в @ControllerAdvice

2024-02-26 04:44 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +    private FilmStorage filmStorage;
обрати внимание на этот комментарий

2024-02-26 04:44 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +public class FilmService {
также в сервисах необходимо добавить логирование всех операций с сущностями(создание, обновление, удаление, получение)

2024-02-26 04:44 UTC, johnskyi commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +public class UserService {
аналогичный комментарий про логирование

2024-02-26 16:52 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +public class FilmService {
Здесь не понял, в чем смысл логирования.
У нас есть контроллер, который по сути является прокси, который тупо пробрасывает все запросы в класс сервиса.
Сначала мы логируем операцию (с параметрами) в контроллере, и потом опять логируем фактически то же самое, но уже в сервисе.
Имхо, это несколько избыточно. Или здесь какая-то другая логика?

2024-02-27 08:55 UTC, closed without merging