Add database
SidyakinV/java-filmorate pull request #8
Opened 2024-03-22 09:02 UTC by SidyakinV

2024-03-22 17:10 UTC, TomattmanYandex requested changes
Привет есть пара вещей на исправление, плюс в проекте должна быть картинка со схемой базы данных

2024-03-22 17:10 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    @Autowired
зачем сразу и @autovired и @RequiredArgsConstructor

2024-03-22 17:10 UTC, TomattmanYandex commented on src/main/resources/data.sql
> +SELECT id, name FROM (
Как то переусложнено

2024-03-22 17:10 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private Long lastId = 0L;
мне кажется этот класс можно удалить, ну или стоит оставить его компонентов и разобраться с квалифаерами

2024-03-22 17:10 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet(
фильмы вернутся без жанров рейтингов

2024-03-22 17:43 UTC, SidyakinV commented
> Привет есть пара вещей на исправление, плюс в проекте должна быть картинка со схемой базы данных
Да, есть такое дело
https://github.com/SidyakinV/java-filmorate/blob/add-database/StructDB.png

2024-03-22 18:52 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    @Autowired
Удалил @autowired. Их много оказалось :)

2024-03-22 19:01 UTC, SidyakinV commented on src/main/resources/data.sql
> +SELECT id, name FROM (
Для Postman'а нужна инициализация справочников. Скрипт data.sql, если я правильно понял, выполняется при каждом запуске. Соответственно, сделано условие not exists, по которому данные не вставляются, если таблица непустая.

2024-03-23 05:02 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private Long lastId = 0L;
Скорее всего, цель спринта - научиться работать с разными классами, иначе бы в ТЗ было бы прямо сказано, что старые можно удалить. Для этих целей я использовал аннотацию @Primary, т.к. мне показалось это более простым вариантом. Переделал на @Qualifier.

2024-03-23 10:43 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        SqlRowSet filmRows = jdbcTemplate.queryForRowSet(
Рейтинг и жанры заполняются в filmFromRowSet

2024-03-23 10:48 UTC, SidyakinV commented
> Привет есть пара вещей на исправление, плюс в проекте должна быть картинка со схемой базы данных

Есть картинка: https://github.com/SidyakinV/java-filmorate/blob/main/StructDB.png
И краткое описание в readme.md тоже сделал.

2024-03-23 13:35 UTC, TomattmanYandex reviewed
Картинки со схемой базы данных все еще нету в пулл реквесте (но ты добавил ссылку на нее в комменте поэтому проблемы нету)
Комментарий про дополнительные запросы в базу обязательный к исправлению, посмотри чтобы везде где мы получаем данные было максимум 3 запроса в базу

2024-03-23 13:35 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private Long lastId = 0L;
отлично, оба варианта хороши, главное что этот тоже компонент)

2024-03-23 13:35 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setGenres(genreStorage.getFilmGenres(film.getId()));
у тебя для каждого фильма будет сделано 2 дополнительных запроса в базу данных
MPA следует добавлять через Join в запросе жанры либо тоже через join
либо в сервисе отдельным запросом в genreDbStorage
при чем для  любого количества фильмов должен быть только один запрос за жанрами

2024-03-24 06:30 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setGenres(genreStorage.getFilmGenres(film.getId()));
Запросы подправил.
По картинке - в промежуточном ТЗ ничего не говорилось про новые ветки, поэтому все изменения залил в main.

2024-03-24 15:20 UTC, TomattmanYandex requested changes
Привет, над логикой хранилищ надо еще поработать
как обработать жанры получше я написал
плюс надо убрать зависимость хранилищ друг от друга

также еще раз пройдись по всем хранилищам баз данных и проверь чтобы было минимум запросов

2024-03-24 15:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        if (filmId != 0) {
очень нехорошая логика
1) до нее тяжело докопаться, 
2) 0 вполне валидный идентификатор для фильма,

лучше перегрузить метод, сделать один с параметром, второй без, чем пихать вот такое вот

2024-03-24 15:20 UTC, TomattmanYandex commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Map<Long, List<Genre>> filmGenres = genreStorage.getCommonFilmGenres(0L);
тут все еще надо поправить
1) обычно хранилища не взаимодействуют друг с другом, так очень большой шанс напороться на циклическую зависимость
сервис получил фильмы из одного хранилища, получил жанры с другого хранилища и их сгруппировал
ну либо тут было бы удобнее, получил фильмы с одного хранилища и передал их в другое хранилище на заполнение
2) почему в аргументах 0? или аргумент неправильный, либо где то логика сделана плохо (я там комент оставил)

теперь рекомендация, как это исправить
сервис получает все фильмы как сейчас (но без жанров)
потом вызывает метод из хранилища жанров setGenresToFilms(List<Film>)
А этот метод внутри себя собирает все идентификаторы фильмов
делает ОДИН запрос в базу со всеми этими идентификаторами(что то типа Select film_id, genre_name с двух связанных таблиц с Join)
а потом пройти по резалт сету и проставить фильмам нужные жанры

2024-03-25 11:11 UTC, SidyakinV commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        Map<Long, List<Genre>> filmGenres = genreStorage.getCommonFilmGenres(0L);
Привет!
Подправил замечания по логике хранилищ. Дополнительно перенес из них все проверки в слой сервиса, а то как-то не совсем логично получалось - что-то в одном месте проверяется, что-то в другом.
По заполнению жанров фильмов и друзей пользователей. Мне не очень понравилась идея заполнять эти данные на уровне сервиса. Если я запрашиваю данные, к примеру, по фильмам, то логично предположить, что из хранилища мне сразу вернется полный набор данных, а не какая-то его "кастрированная" версия, и я не должен помнить о том, что надо еще что-то там дозаполнить. К тому же, такой объект, как жанры фильмов, имхо, по логике все-таки больше относятся к фильмам, нежели к жанрам. Поэтому заполнение сделал в том же хранилище.

2024-03-25 18:37 UTC, TomattmanYandex approved these changes
Привет, 
модификаторы доступа обязательно простаявляем, так что сделай это к следующему спринту, а лучше сразу доп коммитом, 
а в целом принято

2024-03-30 05:28 UTC, merged